# Generated by Django 5.2.7 on 2025-10-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('sitio', models.URLField(blank=True, verbose_name='Sitio web')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('Tinto', 'Tinto'), ('Blanco', 'Blanco'), ('Rosado', 'Rosado'), ('Espumoso', 'Espumoso')], max_length=20, verbose_name='Tipo')),
                ('varietal', models.CharField(max_length=100, verbose_name='Varietal')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinos', to='bodegaApp.bodega', verbose_name='Bodega')),
            ],
        ),
    ]
